language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install -r requirements.txt
  - pip install coverage coveralls --use-mirrors

script:
  - flake8
  - coverage run --source=python tests.py
  - coverage report


after_success: coveralls
